export const S = {
  // Layout
  page: {
    minHeight: "100vh",
    background: "#fafaf8",
    fontFamily: "'Georgia', 'Times New Roman', serif",
    color: "#1a1a18",
  },
  // Auth screens
  authWrap: {
    minHeight: "100vh",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    background: "#fafaf8",
  },
  authLeft: {
    background: "#1a1a18",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "48px",
    position: "relative",
    overflow: "hidden",
  },
  authRight: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "48px",
  },
  authForm: {
    width: "100%",
    maxWidth: 380,
  },
  // Inputs
  inputWrap: { marginBottom: 16, position: "relative" },
  label: {
    display: "block",
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#6b6b62",
    marginBottom: 6,
    fontFamily: "'Georgia', serif",
  },
  input: {
    width: "100%",
    padding: "11px 14px",
    fontSize: 14,
    border: "1.5px solid #e2e2dc",
    borderRadius: 8,
    background: "white",
    color: "#1a1a18",
    outline: "none",
    fontFamily: "'Georgia', serif",
    boxSizing: "border-box",
    transition: "border-color 0.15s",
  },
  // Buttons
  btnPrimary: {
    width: "100%",
    padding: "12px 20px",
    background: "#1a1a18",
    color: "#fafaf8",
    border: "none",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: "0.04em",
    cursor: "pointer",
    fontFamily: "'Georgia', serif",
    transition: "opacity 0.15s",
  },
  btnSecondary: {
    padding: "9px 16px",
    background: "transparent",
    color: "#1a1a18",
    border: "1.5px solid #e2e2dc",
    borderRadius: 8,
    fontSize: 13,
    cursor: "pointer",
    fontFamily: "'Georgia', serif",
    transition: "border-color 0.15s, background 0.15s",
  },
  btnSm: {
    padding: "7px 13px",
    background: "#1a1a18",
    color: "#fafaf8",
    border: "none",
    borderRadius: 7,
    fontSize: 12,
    cursor: "pointer",
    fontFamily: "'Georgia', serif",
    display: "flex",
    alignItems: "center",
    gap: 5,
  },
  // Nav
  nav: {
    height: 56,
    background: "white",
    borderBottom: "1px solid #e8e8e3",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 32px",
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  navBrand: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 15,
    fontWeight: 700,
    letterSpacing: "-0.3px",
    color: "#1a1a18",
  },
  navLinks: {
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  navLink: (active) => ({
    padding: "6px 14px",
    borderRadius: 7,
    fontSize: 13,
    color: active ? "#1a1a18" : "#6b6b62",
    background: active ? "#f0f0eb" : "transparent",
    cursor: "pointer",
    border: "none",
    fontFamily: "'Georgia', serif",
    fontWeight: active ? 600 : 400,
    transition: "all 0.15s",
  }),
  // Cards
  card: {
    background: "white",
    border: "1px solid #e8e8e3",
    borderRadius: 12,
    padding: "22px 24px",
  },
  // Error / success
  error: {
    padding: "10px 14px",
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: 8,
    fontSize: 13,
    color: "#dc2626",
    marginBottom: 16,
    fontFamily: "'Georgia', serif",
  },
  success: {
    padding: "10px 14px",
    background: "#f0fdf4",
    border: "1px solid #bbf7d0",
    borderRadius: 8,
    fontSize: 13,
    color: "#16a34a",
    marginBottom: 16,
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontFamily: "'Georgia', serif",
  },
};